export const countries = [
  // 🌏 Asia
  { name: "Afghanistan", code: "+93", flag: "🇦🇫" },
  { name: "Armenia", code: "+374", flag: "🇦🇲" },
  { name: "Azerbaijan", code: "+994", flag: "🇦🇿" },
  { name: "Bahrain", code: "+973", flag: "🇧🇭" },
  { name: "Bangladesh", code: "+880", flag: "🇧🇩" },
  { name: "Bhutan", code: "+975", flag: "🇧🇹" },
  { name: "Brunei", code: "+673", flag: "🇧🇳" },
  { name: "Cambodia", code: "+855", flag: "🇰🇭" },
  { name: "China", code: "+86", flag: "🇨🇳" },
  { name: "India", code: "+91", flag: "🇮🇳" },
  { name: "Indonesia", code: "+62", flag: "🇮🇩" },
  { name: "Japan", code: "+81", flag: "🇯🇵" },
  { name: "Kazakhstan", code: "+7", flag: "🇰🇿" },
  { name: "Kuwait", code: "+965", flag: "🇰🇼" },
  { name: "Laos", code: "+856", flag: "🇱🇦" },
  { name: "Malaysia", code: "+60", flag: "🇲🇾" },
  { name: "Maldives", code: "+960", flag: "🇲🇻" },
  { name: "Mongolia", code: "+976", flag: "🇲🇳" },
  { name: "Myanmar", code: "+95", flag: "🇲🇲" },
  { name: "Nepal", code: "+977", flag: "🇳🇵" },
  { name: "Pakistan", code: "+92", flag: "🇵🇰" },
  { name: "Philippines", code: "+63", flag: "🇵🇭" },
  { name: "Qatar", code: "+974", flag: "🇶🇦" },
  { name: "Saudi Arabia", code: "+966", flag: "🇸🇦" },
  { name: "Singapore", code: "+65", flag: "🇸🇬" },
  { name: "South Korea", code: "+82", flag: "🇰🇷" },
  { name: "Sri Lanka", code: "+94", flag: "🇱🇰" },
  { name: "Taiwan", code: "+886", flag: "🇹🇼" },
  { name: "Thailand", code: "+66", flag: "🇹🇭" },
  { name: "Vietnam", code: "+84", flag: "🇻🇳" },
  { name: "United Arab Emirates", code: "+971", flag: "🇦🇪" },
  { name: "Turkey", code: "+90", flag: "🇹🇷" },
  { name: "Iran", code: "+98", flag: "🇮🇷" },
  { name: "Israel", code: "+972", flag: "🇮🇱" },

  // 🌍 Europe
  { name: "United Kingdom", code: "+44", flag: "🇬🇧" },
  { name: "France", code: "+33", flag: "🇫🇷" },
  { name: "Germany", code: "+49", flag: "🇩🇪" },
  { name: "Italy", code: "+39", flag: "🇮🇹" },
  { name: "Spain", code: "+34", flag: "🇪🇸" },
  { name: "Portugal", code: "+351", flag: "🇵🇹" },
  { name: "Netherlands", code: "+31", flag: "🇳🇱" },
  { name: "Belgium", code: "+32", flag: "🇧🇪" },
  { name: "Switzerland", code: "+41", flag: "🇨🇭" },
  { name: "Sweden", code: "+46", flag: "🇸🇪" },
  { name: "Norway", code: "+47", flag: "🇳🇴" },
  { name: "Denmark", code: "+45", flag: "🇩🇰" },
  { name: "Finland", code: "+358", flag: "🇫🇮" },
  { name: "Poland", code: "+48", flag: "🇵🇱" },
  { name: "Czech Republic", code: "+420", flag: "🇨🇿" },
  { name: "Austria", code: "+43", flag: "🇦🇹" },
  { name: "Hungary", code: "+36", flag: "🇭🇺" },
  { name: "Greece", code: "+30", flag: "🇬🇷" },
  { name: "Romania", code: "+40", flag: "🇷🇴" },
  { name: "Ukraine", code: "+380", flag: "🇺🇦" },
  { name: "Ireland", code: "+353", flag: "🇮🇪" },
  { name: "Iceland", code: "+354", flag: "🇮🇸" },
  { name: "Russia", code: "+7", flag: "🇷🇺" },

  // 🌎 Americas
  { name: "United States", code: "+1", flag: "🇺🇸" },
  { name: "Canada", code: "+1", flag: "🇨🇦" },
  { name: "Mexico", code: "+52", flag: "🇲🇽" },
  { name: "Brazil", code: "+55", flag: "🇧🇷" },
  { name: "Argentina", code: "+54", flag: "🇦🇷" },
  { name: "Chile", code: "+56", flag: "🇨🇱" },
  { name: "Colombia", code: "+57", flag: "🇨🇴" },
  { name: "Peru", code: "+51", flag: "🇵🇪" },
  { name: "Venezuela", code: "+58", flag: "🇻🇪" },
  { name: "Uruguay", code: "+598", flag: "🇺🇾" },
  { name: "Paraguay", code: "+595", flag: "🇵🇾" },
  { name: "Ecuador", code: "+593", flag: "🇪🇨" },
  { name: "Bolivia", code: "+591", flag: "🇧🇴" },
  { name: "Costa Rica", code: "+506", flag: "🇨🇷" },
  { name: "Panama", code: "+507", flag: "🇵🇦" },
  { name: "Cuba", code: "+53", flag: "🇨🇺" },
  { name: "Dominican Republic", code: "+1-809", flag: "🇩🇴" },
  { name: "Puerto Rico", code: "+1-787", flag: "🇵🇷" },
  { name: "Jamaica", code: "+1-876", flag: "🇯🇲" },
  { name: "Haiti", code: "+509", flag: "🇭🇹" },
  { name: "Honduras", code: "+504", flag: "🇭🇳" },
  { name: "Guatemala", code: "+502", flag: "🇬🇹" },
  { name: "Nicaragua", code: "+505", flag: "🇳🇮" },
  { name: "Belize", code: "+501", flag: "🇧🇿" },
  { name: "Trinidad and Tobago", code: "+1-868", flag: "🇹🇹" },
  { name: "Bahamas", code: "+1-242", flag: "🇧🇸" },
  { name: "Barbados", code: "+1-246", flag: "🇧🇧" },
  { name: "Guyana", code: "+592", flag: "🇬🇾" },
  { name: "Suriname", code: "+597", flag: "🇸🇷" },

  // 🌍 Africa
  { name: "South Africa", code: "+27", flag: "🇿🇦" },
  { name: "Egypt", code: "+20", flag: "🇪🇬" },
  { name: "Nigeria", code: "+234", flag: "🇳🇬" },
  { name: "Kenya", code: "+254", flag: "🇰🇪" },
  { name: "Ethiopia", code: "+251", flag: "🇪🇹" },
  { name: "Morocco", code: "+212", flag: "🇲🇦" },
  { name: "Algeria", code: "+213", flag: "🇩🇿" },
  { name: "Tunisia", code: "+216", flag: "🇹🇳" },
  { name: "Tanzania", code: "+255", flag: "🇹🇿" },
  { name: "Uganda", code: "+256", flag: "🇺🇬" },
  { name: "Ghana", code: "+233", flag: "🇬🇭" },
  { name: "Senegal", code: "+221", flag: "🇸🇳" },
  { name: "Ivory Coast", code: "+225", flag: "🇨🇮" },
  { name: "Cameroon", code: "+237", flag: "🇨🇲" },
  { name: "Zimbabwe", code: "+263", flag: "🇿🇼" },
  { name: "Zambia", code: "+260", flag: "🇿🇲" },
  { name: "Sudan", code: "+249", flag: "🇸🇩" },
  { name: "Mozambique", code: "+258", flag: "🇲🇿" },
  { name: "Madagascar", code: "+261", flag: "🇲🇬" },
  { name: "Botswana", code: "+267", flag: "🇧🇼" },

  // 🌏 Oceania
  { name: "Australia", code: "+61", flag: "🇦🇺" },
  { name: "New Zealand", code: "+64", flag: "🇳🇿" },
  { name: "Fiji", code: "+679", flag: "🇫🇯" },
  { name: "Papua New Guinea", code: "+675", flag: "🇵🇬" },
  { name: "Samoa", code: "+685", flag: "🇼🇸" },
  { name: "Tonga", code: "+676", flag: "🇹🇴" },
  { name: "Vanuatu", code: "+678", flag: "🇻🇺" },
];
